### ISSUE TITLE
Twitter permissions too broad

### ISSUE THREAD

**Issue by cablespaghetti** [Drakuwa/Fridge#2]
Hi. Great app! I had the idea today and then discovered you'd already developed it!

The one thing I spotted is that if you log in with Twitter it asks for permission to "Update your profile" and "Post tweets for you". It would be good if it didn't request these, as there is no need.

Thanks

**Comment by Drakuwa** [comment]
I've updated the Fridge Twitter application permission model to "Read Only". It' should be available in a couple of minutes.
